# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='img_url',
            field=models.CharField(default='./static/img/default_user.png', max_length=250),
        ),
    ]
