# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coachprofile_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='rate_counter',
            field=models.IntegerField(default=0),
        ),
    ]
