# Generated by Django 2.1.2 on 2019-01-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_plan_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='schedule',
        ),
    ]
